name: test

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.17
          - 1.16
        example:
          - c
          - cpp
          - gorm
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build goxx
        uses: docker/bake-action@v1
        with:
          targets: go-${{ matrix.go_version }}
          set: |
            *.tags=localhost:5000/goxx:${{ matrix.go_version }}
          push: true
      -
        name: Build example
        uses: docker/bake-action@v1
        with:
          files: ./examples/${{ matrix.example }}/docker-bake.hcl
          targets: artifact-all
          set: |
            *.context=./examples/${{ matrix.example }}
        env:
          GOXX_BASE: localhost:5000/goxx:${{ matrix.go_version }}
